name: "Update stackage.nix"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-stackage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v15
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= loony-tools:pr9m4BkM/5/eSTZlkQyRt57Jz7OMBxNSUiMC4FkcNfk= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
            substituters = https://cache.iog.io https://cache.zw3rk.com https://cache.nixos.org/
      - name: "Update stackage.nix"
        run: |
          nix build github:input-output-hk/haskell.nix#haskell-nix.nix-tools.ghc8107.project.hsPkgs.nix-tools.components.exes.lts-to-nix -o lts-to-nix
          git submodule update --init
          LTS_TO_NIX=lts-to-nix/bin/lts-to-nix ./update.sh
      - name: Commit and push changes
        run: |
          git config --local user.email "devops+nix-tools@iohk.io"
          git config --local user.name "IOHK"
          git add .
          git commit -m "Automatic Update"
          git push